In [1]:
import pandas as pd

In [2]:
data = {'names':['Sara Moreno 34',
                 'jUAn GOMez 23',
                 'CArlos mArtinez 89',
                 'Alfredo VelaZques 3',
                 'luis Mora 56',
                 '@freddier #platzi 10',pd.NA]}

In [5]:
df = pd.DataFrame(data)
df

names
0        Sara Moreno 34
1         jUAn GOMez 23
2    CArlos mArtinez 89
3   Alfredo VelaZques 3
4          luis Mora 56
5  @freddier #platzi 10
6                  <NA>

In [ ]:
df['names'].str.lower()

0          sara moreno 34
1           juan gomez 23
2      carlos martinez 89
3     alfredo velazques 3
4            luis mora 56
5    @freddier #platzi 10
6                    <NA>
Name: names, dtype: object

In [ ]:
df['names'].str.upper()

0          SARA MORENO 34
1           JUAN GOMEZ 23
2      CARLOS MARTINEZ 89
3     ALFREDO VELAZQUES 3
4            LUIS MORA 56
5    @FREDDIER #PLATZI 10
6                    <NA>
Name: names, dtype: object

In [ ]:
df['names'].str.capitalize()

0          Sara moreno 34
1           Juan gomez 23
2      Carlos martinez 89
3     Alfredo velazques 3
4            Luis mora 56
5    @freddier #platzi 10
6                    <NA>
Name: names, dtype: object

In [10]:
df['names'].str.len()

0      14
1      13
2      18
3      19
4      12
5      20
6    <NA>
Name: names, dtype: object

In [13]:
df['names'].str.split(' ')

0          [Sara, Moreno, 34]
1           [jUAn, GOMez, 23]
2      [CArlos, mArtinez, 89]
3     [Alfredo, VelaZques, 3]
4            [luis, Mora, 56]
5    [@freddier, #platzi, 10]
6                        <NA>
Name: names, dtype: object

In [ ]:
df['names'].str.split('#')

0           [Sara Moreno 34]
1            [jUAn GOMez 23]
2       [CArlos mArtinez 89]
3      [Alfredo VelaZques 3]
4             [luis Mora 56]
5    [@freddier , platzi 10]
6                       <NA>
Name: names, dtype: object

In [ ]:
df['names'].str[:5]

0    Sara 
1    jUAn 
2    CArlo
3    Alfre
4    luis 
5    @fred
6     <NA>
Name: names, dtype: object

In [ ]:
df['names'].str[-5:]

0    no 34
1    ez 23
2    ez 89
3    ues 3
4    ra 56
5    zi 10
6     <NA>
Name: names, dtype: object

In [ ]:
df['names'].str.replace('Alfredo','Antonio')

0          Sara Moreno 34
1           jUAn GOMez 23
2      CArlos mArtinez 89
3     Antonio VelaZques 3
4            luis Mora 56
5    @freddier #platzi 10
6                    <NA>
Name: names, dtype: object

In [ ]:
df['names'].str.findall('ara')

0    [ara]
1       []
2       []
3       []
4       []
5       []
6     <NA>
Name: names, dtype: object

In [ ]:
df['names'].str.contains('or')

0     True
1    False
2    False
3    False
4     True
5    False
6     <NA>
Name: names, dtype: object

In [ ]:
df['names'].str.lower().str.count('a')

0       2
1       1
2       2
3       2
4       1
5       1
6    <NA>
Name: names, dtype: object

In [ ]:
df['names'].str.extract('([0-9]+)', expand=False)

0     34
1     23
2     89
3      3
4     56
5     10
6    NaN
Name: names, dtype: object

In [ ]:
df['names'].str.replace('@[^\s]+','')

0         Sara Moreno 34
1          jUAn GOMez 23
2     CArlos mArtinez 89
3    Alfredo VelaZques 3
4           luis Mora 56
5             #platzi 10
6                   <NA>
Name: names, dtype: object

In [17]:
#MUESTRA HASTA 2 CIFRAS DECIMALES (PANDAS)
pd.options.display.float_format='{:.2f}'.format

In [27]:
#MUESTRA HASTA 2 CIFRAS DECIMALES (NUMPY)
import numpy as np
np.set_printoptions(precision=1)

In [31]:
x1= np.random.rand(2,5) * 10
x1

array([[6. , 2.4, 3.2, 7.8, 7.6],
       [9.4, 2.3, 6.4, 6.5, 4.2]])

In [35]:
x2= np.random.rand(2,5) * -1
x2

array([[-0.2, -0.6, -0.4, -0.6, -0.3],
       [-0.7, -0. , -0.8, -0.5, -0. ]])

In [36]:
np.concatenate([x1,x2])

array([[ 6. ,  2.4,  3.2,  7.8,  7.6],
       [ 9.4,  2.3,  6.4,  6.5,  4.2],
       [-0.2, -0.6, -0.4, -0.6, -0.3],
       [-0.7, -0. , -0.8, -0.5, -0. ]])

In [38]:
np.concatenate([x1,x2]).shape


(4, 5)

In [39]:
np.concatenate([x1,x2], axis=1)

array([[ 6. ,  2.4,  3.2,  7.8,  7.6, -0.2, -0.6, -0.4, -0.6, -0.3],
       [ 9.4,  2.3,  6.4,  6.5,  4.2, -0.7, -0. , -0.8, -0.5, -0. ]])

In [42]:
s1 = pd.Series(x1[0], index=['a','b','c','d','e'])
s1

a   6.04
b   2.36
c   3.20
d   7.85
e   7.63
dtype: float64

In [44]:
s2 = pd.Series(x2[0], index=['c','d','e','f','g'])
s2

c   -0.17
d   -0.56
e   -0.43
f   -0.61
g   -0.32
dtype: float64

In [45]:
pd.concat([s1,s2])

a    6.04
b    2.36
c    3.20
d    7.85
e    7.63
c   -0.17
d   -0.56
e   -0.43
f   -0.61
g   -0.32
dtype: float64

In [46]:
pd.concat([s1,s2],axis=1)

0     1
a 6.04   nan
b 2.36   nan
c 3.20 -0.17
d 7.85 -0.56
e 7.63 -0.43
f  nan -0.61
g  nan -0.32

In [47]:
s1.reset_index(drop=True)

0   6.04
1   2.36
2   3.20
3   7.85
4   7.63
dtype: float64

In [49]:
df1= pd.DataFrame(np.random.rand(3,2)*10, columns=['a','b'])
df1

a    b
0 6.40 5.45
1 3.91 8.49
2 4.24 7.33

In [50]:
df2= pd.DataFrame(np.random.rand(3,2)*-1, columns=['a','b'], index=[2,3,4])
df2

a     b
2 -0.37 -0.89
3 -0.07 -0.82
4 -0.39 -0.96

In [51]:
pd.concat([df1,df2])

a     b
0  6.40  5.45
1  3.91  8.49
2  4.24  7.33
2 -0.37 -0.89
3 -0.07 -0.82
4 -0.39 -0.96

In [52]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 6.40 5.45   nan   nan
1 3.91 8.49   nan   nan
2 4.24 7.33 -0.37 -0.89
3  nan  nan -0.07 -0.82
4  nan  nan -0.39 -0.96

In [53]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 4.24 7.33 -0.37 -0.89

In [54]:
df1.append(df2)

a     b
0  6.40  5.45
1  3.91  8.49
2  4.24  7.33
2 -0.37 -0.89
3 -0.07 -0.82
4 -0.39 -0.96

In [55]:
df1.append(df2).append(df2)

a     b
0  6.40  5.45
1  3.91  8.49
2  4.24  7.33
2 -0.37 -0.89
3 -0.07 -0.82
4 -0.39 -0.96
2 -0.37 -0.89
3 -0.07 -0.82
4 -0.39 -0.96

In [56]:
df1.T

0    1    2
a 6.40 3.91 4.24
b 5.45 8.49 7.33

In [57]:
df1.T.append(df2.T).T

a    b     a     b
0 6.40 5.45   nan   nan
1 3.91 8.49   nan   nan
2 4.24 7.33 -0.37 -0.89
3  nan  nan -0.07 -0.82
4  nan  nan -0.39 -0.96

In [58]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 6.40 5.45   nan   nan
1 3.91 8.49   nan   nan
2 4.24 7.33 -0.37 -0.89
3  nan  nan -0.07 -0.82
4  nan  nan -0.39 -0.96